# Linear Algebra with SciPy

The main Python package for linear algebra is the SciPy subpackage [`scipy.linalg`](https://docs.scipy.org/doc/scipy/reference/linalg.html) which builds on NumPy. Let's import both packages:

In [1]:
import numpy as np
import scipy.linalg as la

## NumPy Arrays

Let's begin with a quick review of [NumPy arrays](../../scipy/numpy/). We can think of a 1D NumPy array as a list of numbers. We can think of a 2D NumPy array as a matrix. And we can think of a 3D array as a cube of numbers.
When we select a row or column from a 2D NumPy array, the result is a 1D NumPy array (called a [slice](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#basic-slicing-and-indexing)). This is different from MATLAB where when you select a column from a matrix it's returned as a column vector which is a 2D MATLAB matrix.

It can get a bit confusing and so we need to keep track of the shape, size and dimension of our NumPy arrays.

### Array Attributes

Create a 1D (one-dimensional) NumPy array and verify its dimensions, shape and size.

In [2]:
a = np.array([1,3,-2,1])
print(a)

[ 1  3 -2  1]


Verify the number of dimensions:

In [3]:
a.ndim

1

Verify the shape of the array:

In [4]:
a.shape

(4,)

The shape of an array is returned as a [Python tuple](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences). The output in the cell above is a tuple of length 1. And we verify the size of the array (ie. the total number of entries in the array):

In [5]:
a.size

4

Create a 2D (two-dimensional) NumPy array (ie. matrix):

In [6]:
M = np.array([[1,2],[3,7],[-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


Verify the number of dimensions:

In [7]:
M.ndim

2

Verify the shape of the array:

In [8]:
M.shape

(3, 2)

Finally, verify the total number of entries in the array:

In [9]:
M.size

6

Select a row or column from a 2D NumPy array and we get a 1D array:

In [10]:
col = M[:,1] 
print(col)

[2 7 5]


Verify the number of dimensions of the slice:

In [11]:
col.ndim

1

Verify the shape and size of the slice:

In [12]:
col.shape

(3,)

In [13]:
col.size

3

When we select a row of column from a 2D NumPy array, the result is a 1D NumPy array. However, we may want to select a column as a 2D column vector. This requires us to use the [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) method.

For example, create a 2D column vector from the 1D slice selected from the matrix `M` above:

In [14]:
print(col)

[2 7 5]


In [15]:
column = np.array([2,7,5]).reshape(3,1)
print(column)

[[2]
 [7]
 [5]]


Verify the dimensions, shape and size of the array:

In [16]:
print('Dimensions:', column.ndim)
print('Shape:', column.shape)
print('Size:', column.size)

Dimensions: 2
Shape: (3, 1)
Size: 3


The variables `col` and `column` are different types of objects even though they have the "same" data.

In [17]:
print(col)

[2 7 5]


In [18]:
print('Dimensions:',col.ndim)
print('Shape:',col.shape)
print('Size:',col.size)

Dimensions: 1
Shape: (3,)
Size: 3


## Matrix Operations and Functions

### Arithmetic Operations

Recall that arithmetic [array operations](../scipy/numpy/#operations-and-functions) `+`, `-`, `/`, `*` and `**` are performed elementwise on NumPy arrays. Let's create a NumPy array and do some computations:

In [19]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [20]:
M * M

array([[ 9, 16],
       [ 1, 25]])

### Matrix Multiplication

We use the `@` operator to do matrix multiplication with NumPy arrays:

In [21]:
M @ M

array([[ 5, 32],
       [-8, 21]])

Let's compute $2I + 3A - AB$ for

$$
A = \begin{bmatrix}
1 & 3 \\\
-1 & 7
\end{bmatrix}
\ \ \ \
B = \begin{bmatrix}
5 & 2 \\\
1 & 2
\end{bmatrix}
$$

and $I$ is the identity matrix of size 2:

In [22]:
A = np.array([[1,3],[-1,7]])
print(A)

[[ 1  3]
 [-1  7]]


In [23]:
B = np.array([[5,2],[1,2]])
print(B)

[[5 2]
 [1 2]]


In [24]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [25]:
2*I + 3*A - A@B

array([[-3.,  1.],
       [-5., 11.]])

### Matrix Powers

There's no symbol for matrix powers and so we must import the function `matrix_power` from the subpackage `numpy.linalg`.

In [26]:
from numpy.linalg import matrix_power as mpow

In [27]:
M = np.array([[3,4],[-1,5]])
print(M)

[[ 3  4]
 [-1  5]]


In [28]:
mpow(M,2)

array([[ 5, 32],
       [-8, 21]])

In [29]:
mpow(M,5)

array([[-1525,  3236],
       [ -809,    93]])

Compare with the matrix multiplcation operator:

In [30]:
M @ M @ M @ M @ M

array([[-1525,  3236],
       [ -809,    93]])

In [31]:
mpow(M,3)

array([[-17, 180],
       [-45,  73]])

In [32]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

###  Tranpose

We can take the transpose with `.T` attribute:

In [33]:
print(M)

[[ 3  4]
 [-1  5]]


In [34]:
print(M.T)

[[ 3 -1]
 [ 4  5]]


Notice that $M M^T$ is a symmetric matrix:

In [35]:
M @ M.T

array([[25, 17],
       [17, 26]])

### Inverse

We can find the inverse using the function `scipy.linalg.inv`:

In [36]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [37]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Trace

We can find the trace of a matrix using the function `numpy.trace`:

In [38]:
np.trace(A)

5

### Norm

*Under construction*

### Determinant

We find the determinant using the function `scipy.linalg.det`:

In [39]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [40]:
la.det(A)

-2.0

### Dot Product

*Under construction*

## Examples

### Characteristic Polynomials and Cayley-Hamilton Theorem

The characteristic polynomial of a 2 by 2 square matrix $A$ is

$$
p_A(\lambda) = \det(A - \lambda I) = \lambda^2 - \mathrm{tr}(A) \lambda + \mathrm{det}(A)
$$

The [Cayley-Hamilton Theorem](https://en.wikipedia.org/wiki/Cayley%E2%80%93Hamilton_theorem) states that any square matrix satisfies its characteristic polynomial. For a matrix $A$ of size 2, this means that

$$
p_A(A) = A^2 - \mathrm{tr}(A) A + \mathrm{det}(A) I = 0
$$

Let's verify the Cayley-Hamilton Theorem for a few different matrices.

In [41]:
print(A)

[[1 2]
 [3 4]]


In [42]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)
A @ A - trace_A * A + det_A * I

array([[0., 0.],
       [0., 0.]])

Let's do this again for some random matrices:

In [43]:
N = np.random.randint(0,10,[2,2])
print(N)

[[1 9]
 [4 3]]


In [44]:
trace_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)
N @ N - trace_N * N + det_N * I

array([[0., 0.],
       [0., 0.]])

### Projections

The formula to project a vector $v$ onto a vector $w$ is

$$
\mathrm{proj}_w(v) = \frac{v \cdot w}{w \cdot w} w
$$

Let's write a function called `proj` which computes the projection $v$ onto $w$.

In [45]:
def proj(v,w):
    '''Project vector v onto w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w)/np.sum(w * w) * w   # or (v @ w)/(w @ w) * w

In [46]:
proj([1,2,3],[1,1,1])

array([2., 2., 2.])

## Exercises

1. Write a function which takes an input parameter $A$, $i$ and $j$ and returns the dot product of the $i$th and $j$th row (indexing starts at 0).
2. Compute the matrix equation $AB + 2B^2 - I$ for matrices $A = \begin{bmatrix} 3 & 4 \\\ -1 & 2 \end{bmatrix}$ and $B = \begin{bmatrix} 5 & 2 \\\ 8 & -3 \end{bmatrix}$.              